[
    {
        "Friend": {
            "id": "14",
            "user_from": "6",
            "user_to": "30",
            "created": "2013-11-18 16:15:29",
            "approved": "1",
            "activation_code": "9e70354986860194ffb638fbecef351c",
            "activated": "1",
            "blocked": "0",
            "flagged": "0"
        },
        "UserFrom": {
            "id": "6",
            "username": "Thabelo",
            "surname": null,
            "password": "online1",
            "phonenumber": "3334443434",
            "street": "34 bree street",
            "emailaddress": "cafenite@gmail.com",
            "homeaddress1": null,
            "homeaddress2": null,
            "homeprovince": null,
            "homecity": null,
            "homepostalcode": null,
            "homeaddresscords": null,
            "workaddresscords": null,
            "agegroup": null,
            "gender": null,
            "driverslicence": null,
            "workaddress1": null,
            "workaddress2": null,
            "workprovince": null,
            "workcity": null,
            "workpostalcode": null,
            "bday": null,
            "licencedate": null,
            "rating": "0",
            "points": "0",
            "userimage": "img/profile/Linux_Jokes__by_LinuxBeast.png",
            "reference": "123456",
            "parent": "0",
            "userkey": "123456",
            "accountactive": "1",
            "specialoffer": "0",
            "pickdate": "2013-10-07",
            "package": "2",
            "email_notification": "0",
            "facebook_notification": "1",
            "sms_notification": "0",
            "twitter_notification": "0",
            "refmeth": "0",
            "refmail": "0",
            "lift_terms": null
        },
        "UserTo": {
            "id": "30",
            "username": "bruce",
            "surname": "lee",
            "password": "123456",
            "phonenumber": "4566545654",
            "street": "china",
            "emailaddress": "bruce@mailinator.com",
            "homeaddress1": "28 petersen street",
            "homeaddress2": "kraaifontein",
            "homeprovince": " Western Cape ",
            "homecity": " Cape Town ",
            "homepostalcode": "7570",
            "homeaddresscords": "-33.859741, 18.713998",
            "workaddresscords": "-33.919915, 18.423012",
            "agegroup": "26 - 30",
            "gender": " male ",
            "driverslicence": " Code A ",
            "workaddress1": "lower burg street",
            "workaddress2": "cape town",
            "workprovince": " Western Cape ",
            "workcity": " Cape Town ",
            "workpostalcode": "8001",
            "bday": "1984-01-19",
            "licencedate": "2014-01-22",
            "rating": null,
            "points": null,
            "userimage": null,
            "reference": "85204522",
            "parent": null,
            "userkey": null,
            "accountactive": "1",
            "specialoffer": "0",
            "pickdate": "2014-01-23",
            "package": "3",
            "email_notification": "0",
            "facebook_notification": "0",
            "sms_notification": "0",
            "twitter_notification": "0",
            "refmeth": "0",
            "refmail": "",
            "lift_terms": null
        }
    },
    {
        "Friend": {
            "id": "15",
            "user_from": "30",
            "user_to": "41",
            "created": "2013-11-18 16:37:05",
            "approved": "1",
            "activation_code": "54da22517b38f070916f008c9987bc00",
            "activated": "1",
            "blocked": "0",
            "flagged": "0"
        },
        "UserFrom": {
            "id": "30",
            "username": "bruce",
            "surname": "lee",
            "password": "123456",
            "phonenumber": "4566545654",
            "street": "china",
            "emailaddress": "bruce@mailinator.com",
            "homeaddress1": "28 petersen street",
            "homeaddress2": "kraaifontein",
            "homeprovince": " Western Cape ",
            "homecity": " Cape Town ",
            "homepostalcode": "7570",
            "homeaddresscords": "-33.859741, 18.713998",
            "workaddresscords": "-33.919915, 18.423012",
            "agegroup": "26 - 30",
            "gender": " male ",
            "driverslicence": " Code A ",
            "workaddress1": "lower burg street",
            "workaddress2": "cape town",
            "workprovince": " Western Cape ",
            "workcity": " Cape Town ",
            "workpostalcode": "8001",
            "bday": "1984-01-19",
            "licencedate": "2014-01-22",
            "rating": null,
            "points": null,
            "userimage": null,
            "reference": "85204522",
            "parent": null,
            "userkey": null,
            "accountactive": "1",
            "specialoffer": "0",
            "pickdate": "2014-01-23",
            "package": "3",
            "email_notification": "0",
            "facebook_notification": "0",
            "sms_notification": "0",
            "twitter_notification": "0",
            "refmeth": "0",
            "refmail": "",
            "lift_terms": null
        },
        "UserTo": {
            "id": "41",
            "username": "swist4",
            "surname": "pompies",
            "password": "123456",
            "phonenumber": "9998887777",
            "street": null,
            "emailaddress": "swist4@mailinator.com",
            "homeaddress1": null,
            "homeaddress2": null,
            "homeprovince": null,
            "homecity": null,
            "homepostalcode": null,
            "homeaddresscords": null,
            "workaddresscords": null,
            "agegroup": null,
            "gender": null,
            "driverslicence": null,
            "workaddress1": null,
            "workaddress2": null,
            "workprovince": null,
            "workcity": null,
            "workpostalcode": null,
            "bday": null,
            "licencedate": null,
            "rating": null,
            "points": null,
            "userimage": "img/profile/images.jpg",
            "reference": "123457",
            "parent": "30",
            "userkey": null,
            "accountactive": "1",
            "specialoffer": "0",
            "pickdate": "0000-00-00",
            "package": "3",
            "email_notification": "0",
            "facebook_notification": "0",
            "sms_notification": "0",
            "twitter_notification": "0",
            "refmeth": "0",
            "refmail": "0",
            "lift_terms": null
        }
    },
    {
        "Friend": {
            "id": "16",
            "user_from": "47",
            "user_to": "30",
            "created": "2014-01-15 11:35:45",
            "approved": "1",
            "activation_code": "dvdfgvdf",
            "activated": "1",
            "blocked": "0",
            "flagged": "0"
        },
        "UserFrom": {
            "id": "47",
            "username": "clayton",
            "surname": "abrahams",
            "password": "123456",
            "phonenumber": "9998889898",
            "street": "28 petersen straat kraaifonten 7570",
            "emailaddress": "clayton@mailinator.com",
            "homeaddress1": null,
            "homeaddress2": null,
            "homeprovince": null,
            "homecity": null,
            "homepostalcode": null,
            "homeaddresscords": null,
            "workaddresscords": null,
            "agegroup": null,
            "gender": null,
            "driverslicence": null,
            "workaddress1": null,
            "workaddress2": null,
            "workprovince": null,
            "workcity": null,
            "workpostalcode": null,
            "bday": null,
            "licencedate": null,
            "rating": null,
            "points": null,
            "userimage": null,
            "reference": "42547829",
            "parent": null,
            "userkey": null,
            "accountactive": "1",
            "specialoffer": "0",
            "pickdate": "2013-12-31",
            "package": "3",
            "email_notification": "0",
            "facebook_notification": "0",
            "sms_notification": "0",
            "twitter_notification": "0",
            "refmeth": "0",
            "refmail": "",
            "lift_terms": null
        },
        "UserTo": {
            "id": "30",
            "username": "bruce",
            "surname": "lee",
            "password": "123456",
            "phonenumber": "4566545654",
            "street": "china",
            "emailaddress": "bruce@mailinator.com",
            "homeaddress1": "28 petersen street",
            "homeaddress2": "kraaifontein",
            "homeprovince": " Western Cape ",
            "homecity": " Cape Town ",
            "homepostalcode": "7570",
            "homeaddresscords": "-33.859741, 18.713998",
            "workaddresscords": "-33.919915, 18.423012",
            "agegroup": "26 - 30",
            "gender": " male ",
            "driverslicence": " Code A ",
            "workaddress1": "lower burg street",
            "workaddress2": "cape town",
            "workprovince": " Western Cape ",
            "workcity": " Cape Town ",
            "workpostalcode": "8001",
            "bday": "1984-01-19",
            "licencedate": "2014-01-22",
            "rating": null,
            "points": null,
            "userimage": null,
            "reference": "85204522",
            "parent": null,
            "userkey": null,
            "accountactive": "1",
            "specialoffer": "0",
            "pickdate": "2014-01-23",
            "package": "3",
            "email_notification": "0",
            "facebook_notification": "0",
            "sms_notification": "0",
            "twitter_notification": "0",
            "refmeth": "0",
            "refmail": "",
            "lift_terms": null
        }
    }
]