{
    "0": {
        "Stardriveuser": {
            "id": "30",
            "username": "Robin",
            "surname": null,
            "phonenumber": "9876667777",
            "street": "21 jump street",
            "emailaddress": "robinfourie@gmail.com",
            "homeaddress1": "28 petersen street",
            "homeaddress2": "kraaifontein",
            "homeprovince": " Western Cape ",
            "homecity": " Cape Town ",
            "homepostalcode": "7570",
            "homeaddresscords": "-33.859741, 18.713998",
            "workaddresscords": "-33.919553, 18.423397",
            "workaddress1": "1 lower burg street",
            "workaddress2": "foreshore",
            "workprovince": " Western Cape ",
            "workcity": " Cape Town ",
            "workpostalcode": "8001",
            "rating": null,
            "points": null,
            "userimage": "img/profile/douche_in_car.png",
            "reference": "77283467",
            "parent": null,
            "userkey": null,
            "accountactive": "1",
            "specialoffer": "0",
            "pickdate": "2013-10-16",
            "package": "2",
            "email_notification": "0",
            "facebook_notification": "0",
            "twitter_notification": "0",
            "sms_notification": "0",
            "refmeth": "0",
            "refmail": "0",
            "lift_terms": "1",
            "bday": null,
            "licencedate": null,
            "driverslicence": null,
            "gender": null,
            "agegroup": null,
            "vehicles": [
                {
                    "Vehicle": {
                        "id": null,
                        "registration": null
                    },
                    "StardriveusersVehicle": {
                        "icon": null
                    }
                }
            ]
        },
        "Vehicle": [
            {
                "id": "12b94dd8-0a73-11e3-be70-d4bed93bc567",
                "stardriveuser_id": "30",
                "thumbnail": "",
                "vehiclename": "",
                "averagespeed": "0",
                "maxspeed": "0",
                "averagedays": "0",
                "registration": "CL30SRGP",
                "description": "Chevrolet Utility",
                "lastupdated": "0000-00-00 00:00:00",
                "status": "0",
                "make": "",
                "model": "",
                "colour": "",
                "vehicleyear": "",
                "photo": "vehicle_profile/6a579ab63e6aadf9845d3792f4b659c7.jpg",
                "nick_name": "",
                "odo_meter": "0",
                "service_date": "2013-12-23",
                "service_interval": "15 000 km",
                "licence_date": "2014-01-07",
                "avatar": "star_maroon_icon.png"
            },
            {
                "id": "12b94e22-0a73-11e3-be70-d4bed93bc567",
                "stardriveuser_id": "30",
                "thumbnail": "",
                "vehiclename": "",
                "averagespeed": "0",
                "maxspeed": "0",
                "averagedays": "0",
                "registration": "SM65LGGP",
                "description": "Chevrolet Utility",
                "lastupdated": "0000-00-00 00:00:00",
                "status": "0",
                "make": "",
                "model": "",
                "colour": "",
                "vehicleyear": "",
                "photo": "vehicle_profile/25bb0408bbb2b496f0cac1de252b7df5.jpg",
                "nick_name": "",
                "odo_meter": "0",
                "service_date": "2014-01-09",
                "service_interval": "10 000 km",
                "licence_date": "2014-01-21",
                "avatar": "star_pink_icon.png"
            },
            {
                "id": "12b94f22-0a73-11e3-be70-d4bed93bc567",
                "stardriveuser_id": "30",
                "thumbnail": "",
                "vehiclename": "",
                "averagespeed": "0",
                "maxspeed": "0",
                "averagedays": "0",
                "registration": "CM65KDGP",
                "description": "Chevrolet Utility",
                "lastupdated": "0000-00-00 00:00:00",
                "status": "0",
                "make": "",
                "model": "",
                "colour": "",
                "vehicleyear": "",
                "photo":  "vehicle_profile/d420be2cc152b04f8b8bb20de5c9bded.jpg",
                "nick_name": "",
                "odo_meter": "0",
                "service_date": "2014-01-09",
                "service_interval": "15 000 km",
                "licence_date": "2014-01-23",
                "avatar": "star_orange_icon.png"
            }
        ],
        "StardriveusersVehicle": [
            {
                "id": "3",
                "stardriveuser_id": "30",
                "vehicle_id": "none",
                "icon": null
            }
        ]
    },
    "result": "success"
}